version: '3'

tasks:
  build:
    desc: "Build the CLI"
    cmds:
      - "go build -o arabian-nights ."

  default:
    desc: "Run the application."
    cmds:
      - "go run ."

  build-docker:
    desc: "Build a container image using Docker."
    cmds:
      - "docker build -t whiterabbittech/arabian-nights:latest ."
